apiVersion: external-secrets.io/v1beta1

kind: ClusterSecretStore

metadata:

  name: aws-secrets-store

spec:

  provider:

    aws:

      service: SecretsManager

      region: ap-southeast-2

      auth:

        jwt:

          serviceAccountRef:

            name: external-secrets-sa

            namespace: external-secrets 

---

apiVersion: external-secrets.io/v1beta1

kind: ExternalSecret

metadata:

  name: db-secret

  namespace: ren-application-gnp1 # update namespace

spec:

  refreshInterval: "1h"

  secretStoreRef:

    kind: ClusterSecretStore  

    name: aws-secrets-store

  target:

    name: db-secret

  data:

    - secretKey: username  

      remoteRef:

        key: ren/databasegnp  # The full name of the secret in AWS Secrets Manager

        property: username  

    - secretKey: password

      remoteRef:

        key: ren/databasegnp  # The full name of the secret in AWS Secrets Manager

        property: password

---

apiVersion: external-secrets.io/v1beta1

kind: ExternalSecret

metadata:

  name: ren-secret

  namespace:  ren-application-gnp1 # update namespace

spec:

  refreshInterval: "1h"

  secretStoreRef:

    kind: ClusterSecretStore  

    name: aws-secrets-store

  target:

    name: ren-secret

  data:

    - secretKey: clientid  

      remoteRef:

        key: ren/rengnp    # update AWS Secrets Manager secret identifier

        property: clientid  

    - secretKey: clientsecret

      remoteRef:

        key: ren/rengnp    # update AWS Secrets Manager secret identifier

        property: clientsecret  

 

---

apiVersion: external-secrets.io/v1beta1

kind: ExternalSecret

metadata:

  name: zeebe-secret

  namespace: ren-application-gnp1  # update namespace

spec:

  refreshInterval: "1h"

  secretStoreRef:

    kind: ClusterSecretStore  

    name: aws-secrets-store

  target:

    name: zeebe-secret

  data:

    - secretKey: clientid  

      remoteRef:

        key: ren/zeebegnp   # update AWS Secrets Manager secret identifier

        property: clientid  

    - secretKey: clientsecret

      remoteRef:

        key: ren/zeebegnp   # update AWS Secrets Manager secret identifier

        property: clientsecret